const productos = [
    //Indumentaria
    {
        id: 1,
        nombre: "Remera Adidas Codes Photoreal Estampada",
        precio: 40000,
        color: "Blanco",
        descripcion: "Con esta remera adidas la nostalgia se apoderará de vos. Es un homenaje a la cultura del básquet que te transporta de regreso a la época dorada. Luce una impresión fotorrealista que cobra vida mediante una mezcla de estilos de estampado. Su tejido de algodón suave la convertirá en una de tus remeras favoritas.",
        categoria: "Indumentaria",
        subcategoria: "Remeras",
        imagen: "",
    },
    {
        id: 2,
        nombre: "Pantalon Nike Club",
        precio: 127000,
        color: "negro",
        descripcion: "Nuestros pantalones Club Fleece clásicos están confeccionados para ofrecer una comodidad suave y un estilo sencillo. Los puños de los tobillos cuentan con cordones elásticos regulables, por lo que puedes ceñirlos para protegerte del aire fresco o presumir tuszapatillas.",
        categoria: "Indumentaria",
        subcategoria: "Pantalones",
        imagen: "",
    },
    {
        id: 3,
        nombre: "Campera de entrenamiento Puma FLEX STRETCH",
        precio: 120000,
        color: "negro",
        descripcion: "Movete libremente con esta campera de entrenamiento, que presenta un corte regular de alto rendimiento y líneas ergonómicas. Además, le incorporamos tecnología dryCELL para absorber la humedad y puños elásticos. Esta campera le sigue el ritmo a tu estilo de vida activo, en tus rutinas del gimnasio y en los paseos por la ciudad.",
        categoria: "Indumentaria",
        subcategoria: "Camperas",
        imagen: "",
    },
    //Calzado
    {
        id: 4,
        nombre: "Zapatillas de training Disperse XT",
        precio: 47500,
        color: "rojo",
        descripcion: "Te has esforzado mucho, ahora lleva el entrenamiento a un nivel superior con las zapatillas de entrenamiento Disperse XT 3, la última actualización de una línea en el nexo de rendimiento y diseño. Esta reinvención de las versiones anteriores cuenta con tracción de goma por zonas para un control adicional y los mismos materiales super livianos para brindar una máxima agilidad. Entrena mejor y más audaz con elementos de diseño más llamativos.",
        categoria: "Calzado",
        subcategoria: "Deportivo",
        imagen: "",
    },
    {
        id:5,
        nombre: "Nike Pegasus Premium",
        precio: 380000,
        color: "blanco",
        descripcion: "Las Pegasus Premium potencian amortiguación responsiva con tres capas apiladas de nuestras tecnologías más potentes para correr: ZoomX, una unidada Air Zoom esculpida y espuma ReactX Foam. Las Pegasus más responsivas de la historia: proporcionan un retorno de energía como ningún otro. Con una parte superior más ligera que el aire, disminuyen el peso y aumentan la transpirabilidad para que puedas volar más rápido.",
        categoria: "Calzado",
        subcategoria: "Running",
        imagen: "",
    },
    {
        id: 6,
        nombre: "Botines Predator Elite para terreno firme con lengüeta abatible",
        precio: 400000,
        color: "blanco",
        descripcion: "Descubrí la diferencia entre aspirar a marcar y saber que lo harás con los botines adidas Predator, diseñados para marcar goles. Estos botines Elite tienen un exterior HybridTouch con lengüeta plegable y aletas Strikeskin de caucho que ayudan a proporcionar un contacto perfecto con la pelota. La suela Controlframe 2.0 para terreno firme y el cuello adidas PRIMEKNIT están diseñados para proporcionarte una postura estable cuando la portería está a tu merced.",
        categoria: "Calzado",
        subcategoria: "Botines",
        imagen: "",
    },
    //Accesorios
    {
        id: 7,
        nombre: "Gorra Running Shmoo",
        precio: 40000,
        color: "blanco",
        descripcion: "Una gorra clásica de seis paneles, reimaginada y personalizada por Mark Gonzales para adidas Skateboarding, la gorra Shmoo Running presenta una estructura de algodón transpirable, tira ajustable y un diseño exclusivo de The Gonz en 3D con relieve y bordado.",
        categoria: "Accesorios",
        subcategoria: "gorras",
        imagen: "",
    },
    {
        id: 8,
        nombre: "Nike Swoosh",
        precio: 21000,
        color: "negro",
        descripcion: "Confeccionado con una cómoda tela absorbente, el diseño elástico de las muñequeras Nike Swoosh mantiene las manos secas para rendir al máximo cuando el partido se intensifica.",
        categoria: "Accesorios",
        subcategoria: "muñeca",
        imagen: "assets/imgs/munequeraNike.webp",
    },
    {
        id: 9,
        nombre: "Mochila PUMA.BL",
        precio: 100000,
        color: "rojo",
        descripcion: "Esta mochila encarna la audaz filosofía de PUMA.BL. En esta colección, nos sobreponemos a las etiquetas para celebrar a cada individuo por quien es, más allá de juicios y estereotipos. Con una estética elegante y un diseño funcional, esta mochila es tu compañera perfecta para afrontar cada día con confianza y estilo.",
        categoria: "Accesorios",
        subcategoria: "Mochilas",
        imagen: "",
    },
];